### ISSUE TITLE
Error since today

### ISSUE THREAD

**Issue by sembeek** [mampfes/ha_epex_spot#174]
I get the following error for the prices of tomorrow since today.

`200, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='https://www.epexspot.com/en'`

I am running version 2.3.8, it looks like they changed something at the Epexespot.com side and the integration needs to adapt?
I'm using the NL Scraper.

Here is the full log:
`2024-11-22 13:07:56.698 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139834067618688] Error handling message: Unknown error (unknown_error) 
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/websocket_api/commands.py", line 816, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/epex_spot/__init__.py", line 136, in fetch_data
    await c.source.fetch()
  File "/config/custom_components/epex_spot/SourceShell.py", line 103, in fetch
    await self._source.fetch()
  File "/config/custom_components/epex_spot/EPEXSpot/EPEXSpotWeb/__init__.py", line 139, in fetch
    marketdata = await self._fetch_day(delivery_date) + await self._fetch_day(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/epex_spot/EPEXSpot/EPEXSpotWeb/__init__.py", line 146, in _fetch_day
    data = await self._fetch_data(delivery_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/epex_spot/EPEXSpot/EPEXSpotWeb/__init__.py", line 203, in _fetch_data
    return await resp.json()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/aiohttp_client.py", line 80, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1278, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 200, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='https://www.epexspot.com/en'`

Regards,

Sem

**Comment by Schlichi83** [comment]
I have the same issue.

**Comment by lieven121** [comment]
This is fixed on v3 not on v2 for now you can fix it yourself until it is fixed 

![image](https://github.com/user-attachments/assets/8caede28-f32a-45eb-b6e7-2460acb850ba)

**Comment by lieven121** [comment]
Open vscode addon goto /config/custom_components/epex_spot/EPEXSpot/EPEXSpotWeb/__init__.py
and update the lines above

Restart home assistant

**Comment by sembeek** [comment]
Thank you very much, that worked!
I will try to migrate to v3 shortly.

**Comment by lieven121** [comment]
FYI Fixed in ca4ced708f002c1bac062b8f1ad65c917483379b

**Comment by lieven121** [comment]
> @lieven121 Thank you very much, that worked! I will try to migrate to v3 shortly.

Be warned v3 is dev and has breaking changes (price is expressed in currency instead of ct)
i am on v2 for now

**Comment by sembeek** [comment]
> > @lieven121 Thank you very much, that worked! I will try to migrate to v3 shortly.
> 
> Be warned v3 is dev and has breaking changes (price is expressed in currency instead of ct) i am on v2 for now

You are really fast haha.
I saw the breaking change indeed.

**Comment by suaveolent** [comment]
Fixed now with version `2.3.9` or `3.0.0-dev4`
