### ISSUE TITLE
Integration setup failed

### ISSUE THREAD

**Issue by Xrlwyzz** [mampfes/ha_epex_spot#3]
Hi,

I just tried to configure the integration. But regardless if I try awattar or epex web scraper, I always receive these errors in the logs instead of an entity:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/epex_spot/__init__.py", line 25, in async_setup_entry
    shell.add_entry(entry)
  File "/config/custom_components/epex_spot/__init__.py", line 63, in add_entry
    self._hass, self._fetch_callback, timedelta(hour=1)
TypeError: 'hour' is an invalid keyword argument for __new__()

Home assistant is running the tatest version 2022.12.9.

Any idea what I could have done wrong?

**Comment by mampfes** [comment]
Oh, sorry for that. I pushed a broken state by mistake.

**Comment by Xrlwyzz** [comment]
Awesome, after updating it started working right away!
Thank you very much for the fast reply!
